<CalculadoraLayout>:

    GridLayout:
        cols: 1
        rows: 1
        padding: 5
        spacing: 5

        BoxLayout:
            orientation: "vertical"
            spacing: 5

            # FILA 1: PANTALLA + C
            BoxLayout:
                orientation: "horizontal"
                spacing: 5

                Label:
                    id: pantalla
                    text: "0"
                    font_size: 40
                    color: 0, 0, 0, 1
                    size_hint_x: 3
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                Button:
                    text: "C"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    size_hint_x: 1

                    on_press: app.limpiar()

            # FILA 2
            BoxLayout:
                orientation: "horizontal"
                spacing: 5

                Button:
                    text: "7"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "8"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "9"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "*"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

            # FILA 3
            BoxLayout:
                orientation: "horizontal"
                spacing: 5

                Button:
                    text: "4"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "5"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "6"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "/"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

            # FILA 4
            BoxLayout:
                orientation: "horizontal"
                spacing: 5

                Button:
                    text: "1"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "2"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "3"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "-"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

            # FILA 5
            BoxLayout:
                orientation: "horizontal"
                spacing: 5

                Button:
                    text: "0"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "."
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "="
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)

                Button:
                    text: "+"
                    font_size: 30
                    color: 0, 0, 0, 1
                    background_normal: ""
                    background_color: 1, 1, 1, 1
                    on_press: app.presionar_boton(self.text)


CalculadoraLayout: